"""ui_builders.py – extracted UI builder helpers for BREadbeatsWindow.

Auto-generated by _tmp_extract_ui_builders.py.  Each function here was
originally a method of BREadbeatsWindow; the ``self`` parameter has been
replaced by ``win`` (the window instance passed explicitly).
"""

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QGridLayout,
    QGroupBox, QLabel, QSlider, QComboBox, QPushButton, QCheckBox,
    QSpinBox, QDoubleSpinBox, QLineEdit, QTabWidget, QScrollArea,
    QSizePolicy, QMenu, QMenuBar, QMessageBox,
)
from PyQt6.QtCore import Qt, QTimer
from PyQt6.QtGui import QAction, QColor
import pyqtgraph as pg
import numpy as np
from typing import Optional
from functools import partial
from config import BEAT_RANGE_LIMITS, BeatDetectionType, StrokeMode
from widgets import (
    SliderWithLabel, RangeSliderWithLabel, CollapsibleGroupBox,
    NoWheelScrollArea, FFTBinBarGraphCanvas, WaveformLiveCanvas,
    FrequencyDbLiveCanvas, PositionCanvas,
)
from stylesheet import get_thin_scrollbar_style
from logging_utils import get_log_level, log_event, set_log_level

def create_menu_bar(win):
    """Create menu bar with top-level menus for app controls, options, and help."""
    menubar = win.menuBar()
    assert menubar is not None
    
    main_menu = menubar.addMenu("Menu")
    assert main_menu is not None
    
    # Connection submenu
    connection_menu = main_menu.addMenu("Connection")
    assert connection_menu is not None

    connection_settings_action = connection_menu.addAction("Settings...")
    assert connection_settings_action is not None
    connection_settings_action.triggered.connect(win._on_options_connection)

    win.connection_toggle_action = connection_menu.addAction("Connect")
    assert win.connection_toggle_action is not None
    win.connection_toggle_action.triggered.connect(win._on_connect)

    win.connection_test_action = connection_menu.addAction("Test")
    assert win.connection_test_action is not None
    win.connection_test_action.triggered.connect(win._on_test)
    win.connection_test_action.setEnabled(False)

    # Audio Device option
    audio_device_action = main_menu.addAction("Audio Device...")
    assert audio_device_action is not None
    audio_device_action.triggered.connect(win._on_options_audio_device)

    # Device Limits option
    device_limits_action = main_menu.addAction("Device Limits...")
    assert device_limits_action is not None
    device_limits_action.triggered.connect(win._on_device_limits)
    
    # Nerds menu (advanced perf + diagnostics) - inserted near Help later
    nerds_menu = QMenu("Nerds", menubar)
    assert nerds_menu is not None
    
    # FFT Size submenu
    fft_menu = nerds_menu.addMenu("FFT Size (requires restart)")
    assert fft_menu is not None
    fft_sizes = [512, 1024, 2048, 4096, 8192]
    fft_labels = [
        "512 (fast, ~86Hz/bin)",
        "1024 (balanced, ~43Hz/bin)",
        "2048 (good bass, ~21Hz/bin)",
        "4096 (great bass, ~11Hz/bin)",
        "8192 (best bass, ~5Hz/bin)"
    ]
    current_fft = getattr(win.config.audio, 'fft_size', 1024)
    for i, (size, label) in enumerate(zip(fft_sizes, fft_labels)):
        action = fft_menu.addAction(label)
        assert action is not None
        action.triggered.connect(lambda checked, idx=i: win._on_menu_fft_change(idx))
        if size == current_fft:
            action.setCheckable(True)
            action.setChecked(True)
    
    # Spectrum Updates submenu
    spec_menu = nerds_menu.addMenu("Spectrum Updates")
    assert spec_menu is not None
    spec_options = ["Every frame (smooth)", "Every 2 frames (fast)", "Every 4 frames (faster)"]
    spec_values = [1, 2, 4]
    current_skip = getattr(win.config.audio, 'spectrum_skip_frames', 2)
    for i, (label, value) in enumerate(zip(spec_options, spec_values)):
        action = spec_menu.addAction(label)
        assert action is not None
        action.triggered.connect(lambda checked, idx=i: win._on_menu_spectrum_change(idx))
        if value == current_skip:
            action.setCheckable(True)
            action.setChecked(True)

    fft_diag_action = nerds_menu.addAction("FFT Bin Diagnostics...")
    assert fft_diag_action is not None
    fft_diag_action.triggered.connect(win._on_fft_bin_diagnostics)
    
    # Options menu (separate top-level menu)
    options_menu = menubar.addMenu("Options")
    assert options_menu is not None
    
    beat_detection_action = options_menu.addAction("Beat Detection...")
    assert beat_detection_action is not None
    beat_detection_action.triggered.connect(win._on_options_beat_detection)

    motion_settings_action = options_menu.addAction("Motion Settings...")
    assert motion_settings_action is not None
    motion_settings_action.triggered.connect(win._on_options_motion_settings)

    # Spectrum visualizer type submenu
    viz_menu = options_menu.addMenu("Spectrum Type")
    assert viz_menu is not None
    viz_names = ["Waveform", "Freq dB", "Digital FFT"]
    default_viz_index = 0  # Waveform
    win.visualizer_type_combo = QComboBox()  # Hidden combo for state tracking
    win.visualizer_type_combo.addItems(viz_names)
    win.visualizer_type_combo.setCurrentIndex(default_viz_index)
    win._viz_type_actions = []
    for i, name in enumerate(viz_names):
        action = viz_menu.addAction(name)
        assert action is not None
        action.setCheckable(True)
        action.setChecked(i == default_viz_index)
        action.triggered.connect(lambda checked, idx=i: win._on_viz_menu_change(idx))
        win._viz_type_actions.append(action)

    effects_menu = options_menu.addMenu("Effects")
    assert effects_menu is not None

    # Intelligence toggle (unchecking = Simple Mode)
    win.intelligence_enabled_action = effects_menu.addAction("Intelligence")
    assert win.intelligence_enabled_action is not None
    win.intelligence_enabled_action.setCheckable(True)
    win.intelligence_enabled_action.setChecked(bool(getattr(win.config.stroke, 'intelligence_enabled', True)))
    win.intelligence_enabled_action.toggled.connect(win._on_intelligence_toggle)

    # Beats per Rotation submenu (visible only when intelligence is disabled)
    win._beats_per_rotation_menu = effects_menu.addMenu("Beats per Rotation")
    assert win._beats_per_rotation_menu is not None
    win._beats_per_rotation_actions = []
    current_bpr = int(getattr(win.config.stroke, 'simple_mode_beats_per_rotation', 1) or 1)
    for bpr in (1, 2, 4):
        action = win._beats_per_rotation_menu.addAction(f"{bpr}")
        assert action is not None
        action.setCheckable(True)
        action.setChecked(bpr == current_bpr)
        action.triggered.connect(lambda checked, val=bpr: win._on_beats_per_rotation_change(val))
        win._beats_per_rotation_actions.append(action)
    # Only show submenu when intelligence is disabled
    win._beats_per_rotation_menu.menuAction().setVisible(
        not bool(getattr(win.config.stroke, 'intelligence_enabled', True))
    )

    effects_menu.addSeparator()

    win.jitter_effect_action = effects_menu.addAction("Jitter")
    assert win.jitter_effect_action is not None
    win.jitter_effect_action.setCheckable(True)
    win.jitter_effect_action.setChecked(bool(getattr(win.config.jitter, 'enabled', True)))
    win.jitter_effect_action.triggered.connect(win._on_effects_jitter_toggle)

    # Metronome Lock Req'd (moved into Effects menu)
    win.metronome_lock_required_action = effects_menu.addAction("Metronome Lock Req'd")
    assert win.metronome_lock_required_action is not None
    win.metronome_lock_required_action.setCheckable(True)
    win.metronome_lock_required_action.setChecked(bool(getattr(win.config.beat, 'tempo_lock_required', False)))
    win.metronome_lock_required_action.toggled.connect(win._on_tempo_lock_required_toggle)

    developer_controls_action = options_menu.addAction("Developer Controls")
    assert developer_controls_action is not None
    developer_controls_action.triggered.connect(win._open_developer_controls_window)

    nerds_menu.addSeparator()

    # Log level submenu
    log_menu = nerds_menu.addMenu("Log Level")
    assert log_menu is not None
    win._log_level_actions = []
    for level in ["DEBUG", "INFO", "WARNING", "ERROR"]:
        action = log_menu.addAction(level)
        assert action is not None
        action.setCheckable(True)
        action.triggered.connect(lambda checked, lvl=level: win._on_log_level_change(lvl))
        win._log_level_actions.append(action)
    win._sync_log_level_menu(getattr(win.config, 'log_level', 'INFO'))
    
    # Nerds menu should be second-to-last (right before Help)
    menubar.addMenu(nerds_menu)
    
    # Help menu (separate top-level menu)
    help_menu = menubar.addMenu("Help")
    assert help_menu is not None
    
    help_action = help_menu.addAction("Troubleshooting...")
    assert help_action is not None
    help_action.triggered.connect(win._on_help)

    about_action = help_menu.addAction("About")
    assert about_action is not None
    about_action.triggered.connect(win._on_about)


# ── dialog-builder delegates (implementations in dialog_builders.py) ──


def build_motion_options_tab(win) -> QWidget:
    from PyQt6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QCheckBox, QGroupBox, QSpinBox

    content = QWidget()
    layout = QVBoxLayout(content)
    layout.setSpacing(10)

    scroll = NoWheelScrollArea()
    scroll.setWidgetResizable(True)
    scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
    scroll_content = QWidget()
    scroll_layout = QVBoxLayout(scroll_content)
    scroll_layout.setSpacing(10)

    # ===== Silence Gate Controls =====
    silence_group = QGroupBox("Silence Gate (dBFS)")
    silence_layout = QVBoxLayout(silence_group)

    silence_info = QLabel(
        "These thresholds control silence deadzone hysteresis in dBFS.\n"
        "More negative = quieter/more permissive. Open = enter silence, Close = exit silence."
    )
    silence_info.setStyleSheet("color: #aaa; font-size: 11px;")
    silence_layout.addWidget(silence_info)

    silence_open_db = win._silence_threshold_to_db(
        getattr(win.config.stroke, 'silence_threshold', -40.0),
        default_linear=0.001,
    )
    silence_close_db = win._silence_threshold_to_db(
        getattr(win.config.stroke, 'silence_close_threshold', -26.0),
        default_linear=0.01,
    )
    if silence_close_db <= silence_open_db:
        silence_close_db = float(min(0.0, silence_open_db + 1.5))

    silence_open_slider = SliderWithLabel(
        "No Motion Under (dBFS)",
        -90.0,
        -6.0,
        silence_open_db,
        1,
    )
    silence_open_slider.setToolTip("Audio level below this dBFS value enters silence mode (motion stops, dot parks)")

    silence_close_slider = SliderWithLabel(
        "Limited Motion Under (dBFS)",
        -90.0,
        -3.0,
        silence_close_db,
        1,
    )
    silence_close_slider.setToolTip("Audio level must exceed this dBFS value to exit silence mode (motion resumes)")

    def _set_silence_open(v: float) -> None:
        open_v = float(v)
        setattr(win.config.stroke, 'silence_threshold', open_v)
        close_v = win._silence_threshold_to_db(
            getattr(win.config.stroke, 'silence_close_threshold', -26.0),
            default_linear=0.01,
        )
        if close_v <= open_v:
            close_v = float(min(0.0, open_v + 1.5))
            setattr(win.config.stroke, 'silence_close_threshold', close_v)
            silence_close_slider.blockSignals(True)
            silence_close_slider.setValue(close_v)
            silence_close_slider.blockSignals(False)

    def _set_silence_close(v: float) -> None:
        close_v = float(v)
        open_v = win._silence_threshold_to_db(
            getattr(win.config.stroke, 'silence_threshold', -40.0),
            default_linear=0.001,
        )
        if close_v <= open_v:
            close_v = float(min(0.0, open_v + 1.5))
            silence_close_slider.blockSignals(True)
            silence_close_slider.setValue(close_v)
            silence_close_slider.blockSignals(False)
        setattr(win.config.stroke, 'silence_close_threshold', close_v)

    silence_open_slider.valueChanged.connect(_set_silence_open)
    silence_close_slider.valueChanged.connect(_set_silence_close)
    silence_layout.addWidget(silence_open_slider)
    silence_layout.addWidget(silence_close_slider)
    scroll_layout.addWidget(silence_group)

    # ===== Expression Layer Controls =====
    expression_group = QGroupBox("Expression Layer")
    expression_layout = QVBoxLayout(expression_group)

    expr_info = QLabel(
        "Artistic expression: center wandering,\n"
        "direction changes, tension pauses, and session arc."
    )
    expr_info.setStyleSheet("color: #aaa; font-size: 11px;")
    expression_layout.addWidget(expr_info)

    wander_cb = QCheckBox("Center wandering (orbit drifts horizontally)")
    wander_cb.setChecked(bool(getattr(win.config.stroke, 'center_wander_enabled', True)))
    wander_cb.stateChanged.connect(
        lambda state: setattr(win.config.stroke, 'center_wander_enabled', state == 2)
    )
    expression_layout.addWidget(wander_cb)

    wander_max_slider = SliderWithLabel(
        "Wander max offset",
        0.0, 0.50,
        float(getattr(win.config.stroke, 'center_wander_max_x', 0.20) or 0.20),
        2,
    )
    wander_max_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'center_wander_max_x', float(v))
    )
    expression_layout.addWidget(wander_max_slider)

    wander_cycle_slider = SliderWithLabel(
        "Wander cycle (seconds)",
        5.0, 60.0,
        float(getattr(win.config.stroke, 'center_wander_cycle_s', 25.0) or 25.0),
        1,
    )
    wander_cycle_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'center_wander_cycle_s', float(v))
    )
    expression_layout.addWidget(wander_cycle_slider)

    wander_energy_slider = SliderWithLabel(
        "Wander energy influence",
        0.0, 1.0,
        float(getattr(win.config.stroke, 'center_wander_energy_scale', 0.6) or 0.6),
        2,
    )
    wander_energy_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'center_wander_energy_scale', float(v))
    )
    expression_layout.addWidget(wander_energy_slider)

    direction_cb = QCheckBox("Direction changes at phrase boundaries")
    direction_cb.setChecked(bool(getattr(win.config.stroke, 'direction_change_enabled', True)))
    direction_cb.stateChanged.connect(
        lambda state: setattr(win.config.stroke, 'direction_change_enabled', state == 2)
    )
    expression_layout.addWidget(direction_cb)

    direction_interval_slider = SliderWithLabel(
        "Min interval between reversals (s)",
        5.0, 60.0,
        float(getattr(win.config.stroke, 'direction_change_interval_s', 15.0) or 15.0),
        1,
    )
    direction_interval_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'direction_change_interval_s', float(v))
    )
    expression_layout.addWidget(direction_interval_slider)

    direction_drop_slider = SliderWithLabel(
        "Energy change to trigger reversal",
        0.10, 0.80,
        float(getattr(win.config.stroke, 'direction_change_energy_drop', 0.35) or 0.35),
        2,
    )
    direction_drop_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'direction_change_energy_drop', float(v))
    )
    expression_layout.addWidget(direction_drop_slider)

    session_cb = QCheckBox("Session arc (gradual long-term intensity evolution)")
    session_cb.setChecked(bool(getattr(win.config.stroke, 'session_arc_enabled', True)))
    session_cb.stateChanged.connect(
        lambda state: setattr(win.config.stroke, 'session_arc_enabled', state == 2)
    )
    expression_layout.addWidget(session_cb)

    session_influence_slider = SliderWithLabel(
        "Session arc radius influence",
        0.0, 0.30,
        float(getattr(win.config.stroke, 'session_arc_radius_influence', 0.10) or 0.10),
        2,
    )
    session_influence_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'session_arc_radius_influence', float(v))
    )
    expression_layout.addWidget(session_influence_slider)

    scroll_layout.addWidget(expression_group)

    # ===== Post-Silence Volume Ramp =====
    silence_ramp_group = QGroupBox("Post-Silence Volume Ramp")
    silence_ramp_layout = QVBoxLayout(silence_ramp_group)

    silence_ramp_info = QLabel("After silence (track change), reduce volume and slowly\nraise it back over a configurable duration.")
    silence_ramp_info.setStyleSheet("color: #aaa; font-size: 11px;")
    silence_ramp_layout.addWidget(silence_ramp_info)

    vol_reduction_slider = SliderWithLabel(
        "Volume reduction (%)",
        0.0,
        0.50,
        float(getattr(win.config.stroke, 'post_silence_vol_reduction', 0.15) or 0.15),
        2,
    )
    vol_reduction_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'post_silence_vol_reduction', v)
    )
    silence_ramp_layout.addWidget(vol_reduction_slider)

    ramp_dur_slider = SliderWithLabel(
        "Ramp duration (seconds)",
        1.0,
        8.0,
        float(getattr(win.config.stroke, 'post_silence_ramp_seconds', 4.0) or 4.0),
        1,
    )
    ramp_dur_slider.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'post_silence_ramp_seconds', v)
    )
    silence_ramp_layout.addWidget(ramp_dur_slider)

    fade_drop_row = QHBoxLayout()
    fade_drop_label = QLabel("Fade max drop points (out of 100):")
    fade_drop_label.setStyleSheet("color: #ccc;")
    fade_drop_row.addWidget(fade_drop_label)
    fade_drop_spin = QSpinBox()
    fade_drop_spin.setRange(0, 10)
    fade_drop_spin.setSingleStep(1)
    fade_drop_spin.setValue(int(np.clip(getattr(win.config.stroke, 'silence_fade_drop_points', 10) or 10, 0, 10)))
    fade_drop_spin.setToolTip("Caps runtime fade reduction to this many volume points (0-10)")
    fade_drop_spin.valueChanged.connect(
        lambda v: setattr(win.config.stroke, 'silence_fade_drop_points', int(v))
    )
    fade_drop_row.addWidget(fade_drop_spin)
    fade_drop_row.addStretch()
    silence_ramp_layout.addLayout(fade_drop_row)

    scroll_layout.addWidget(silence_ramp_group)

    scroll_layout.addStretch()
    scroll.setWidget(scroll_content)
    layout.addWidget(scroll)
    return content


def create_connection_panel(win) -> QWidget:
    """Connection settings panel - simplified, host/port in Options menu (no visible groupbox)"""
    group = QWidget()
    layout = QHBoxLayout(group)
    layout.setContentsMargins(0, 0, 0, 0)
    
    # Hidden Host/Port widgets (needed for functionality but now in Options menu)
    win.host_edit = QLineEdit(win.config.connection.host)
    win.host_edit.setVisible(False)
    win.port_spin = QSpinBox()
    win.port_spin.setRange(1, 65535)
    win.port_spin.setValue(win.config.connection.port)
    win.port_spin.setVisible(False)
    
    # Connection status / refresh button
    win.status_label = QPushButton("Connect")
    win.status_label.setFixedSize(100, 40)
    win.status_label.setStyleSheet("color: #fff;")
    win.status_label.setToolTip("Reconnect / refresh TCP connection")
    win.status_label.clicked.connect(win._on_connection_refresh)
    layout.addWidget(win.status_label)
    
    return group


def create_control_panel(win) -> QWidget:
    """Main control buttons - audio device selection moved to Options menu (no visible groupbox)"""
    group = QWidget()
    layout = QVBoxLayout(group)
    layout.setContentsMargins(0, 0, 0, 0)
    
    # Hidden audio device widgets (needed for functionality but now in Options menu)
    win.device_combo = QComboBox()
    win._populate_audio_devices()
    win.device_combo.setVisible(False)
    
    # Controls row - all on one row now
    btn_layout = QGridLayout()
    btn_layout.setSpacing(8)
    
    # Start/Stop audio capture
    win.start_btn = QPushButton("▶ Start")
    win.start_btn.clicked.connect(lambda _checked=False: win._on_start_stop())
    win.start_btn.setFixedSize(100, 40)
    win.start_btn.setStyleSheet("color: #0af;")
    start_stack = QVBoxLayout()
    start_stack.setSpacing(2)
    start_stack.addWidget(win.start_btn)
    btn_layout.addLayout(start_stack, 0, 0)
    
    # Play/Pause sending
    win.play_btn = QPushButton("▶ Play")
    win.play_btn.clicked.connect(lambda _checked=False: win._on_play_pause())
    win.play_btn.setEnabled(False)
    win.play_btn.setFixedSize(100, 40)
    win.play_btn.setStyleSheet("color: #0af;")
    play_stack = QVBoxLayout()
    play_stack.setSpacing(2)
    play_stack.addWidget(win.play_btn)
    btn_layout.addLayout(play_stack, 0, 1)

    # Volume slider (0 - 100)
    win.volume_slider = SliderWithLabel("Volume", 0, 100, 100, decimals=0)
    win.volume_slider.label.setFixedWidth(60)
    win.volume_slider.setMinimumWidth(180)
    win.volume_slider.setContentsMargins(0, 0, 0, 0)
    btn_layout.addWidget(win.volume_slider, 0, 2, 1, 1, Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignVCenter)

    # Frequency displays - stacked vertically
    freq_display_layout = QVBoxLayout()
    freq_display_layout.setSpacing(0)
    
    # Carrier Freq display
    win.carrier_freq_label = QLabel("Carrier Freq: off")
    win.carrier_freq_label.setStyleSheet("color: #0af; font-size: 10px;")
    win.carrier_freq_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    freq_display_layout.addWidget(win.carrier_freq_label)
    
    # Pulse Freq display
    win.pulse_freq_label = QLabel("Pulse Freq: off")
    win.pulse_freq_label.setStyleSheet("color: #0af; font-size: 10px;")
    win.pulse_freq_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    freq_display_layout.addWidget(win.pulse_freq_label)
    
    # Pulse Width display
    win.p1_display_label = QLabel("Pulse Width: off")
    win.p1_display_label.setStyleSheet("color: #0af; font-size: 10px;")
    win.p1_display_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    freq_display_layout.addWidget(win.p1_display_label)
    
    # Rise Time display
    win.p3_display_label = QLabel("Rise Time: off")
    win.p3_display_label.setStyleSheet("color: #0af; font-size: 10px;")
    win.p3_display_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    freq_display_layout.addWidget(win.p3_display_label)
    
    freq_display_widget = QWidget()
    freq_display_widget.setLayout(freq_display_layout)
    btn_layout.addWidget(freq_display_widget, 0, 3, 1, 1, Qt.AlignmentFlag.AlignHCenter)

    # Right-side stack: beat indicators
    right_stack = QVBoxLayout()
    right_stack.setSpacing(2)

    # Beat & Downbeat & Metronome Sync indicators (bottom of right stack)
    beat_row = QHBoxLayout()
    beat_row.setSpacing(4)
    win.beat_indicator = QLabel("●")
    win.beat_indicator.setStyleSheet("color: #333; font-size: 20px;")
    win.beat_indicator.setAlignment(Qt.AlignmentFlag.AlignCenter)
    win.beat_indicator.setFixedWidth(24)
    win.beat_indicator.setToolTip("Beat")
    beat_row.addWidget(win.beat_indicator)
    win.downbeat_indicator = QLabel("●")
    win.downbeat_indicator.setStyleSheet("color: #333; font-size: 20px;")
    win.downbeat_indicator.setAlignment(Qt.AlignmentFlag.AlignCenter)
    win.downbeat_indicator.setFixedWidth(24)
    win.downbeat_indicator.setToolTip("Downbeat")
    beat_row.addWidget(win.downbeat_indicator)
    win.metronome_sync_indicator = QLabel("●")
    win.metronome_sync_indicator.setStyleSheet("color: #333; font-size: 20px;")
    win.metronome_sync_indicator.setAlignment(Qt.AlignmentFlag.AlignCenter)
    win.metronome_sync_indicator.setFixedWidth(24)
    win.metronome_sync_indicator.setToolTip("Metronome sync (gray=off, yellow=locking, green=locked)")
    beat_row.addWidget(win.metronome_sync_indicator)
    right_stack.addLayout(beat_row)

    right_stack_widget = QWidget()
    right_stack_widget.setLayout(right_stack)
    btn_layout.addWidget(right_stack_widget, 0, 4, 1, 1, Qt.AlignmentFlag.AlignHCenter)

    for col in range(5):
        btn_layout.setColumnStretch(col, 1)
    layout.addLayout(btn_layout)

    # Beat indicator timer for visual feedback duration
    win.beat_timer = QTimer()
    win.beat_timer.setSingleShot(True)
    win.beat_timer.timeout.connect(win._turn_off_beat_indicator)
    win.beat_indicator_min_duration = 100  # ms

    # Downbeat indicator timer
    win.downbeat_timer = QTimer()
    win.downbeat_timer.setSingleShot(True)
    win.downbeat_timer.timeout.connect(win._turn_off_downbeat_indicator)

    return group


def create_spectrum_panel(win) -> QWidget:
    """Spectrum visualizer panel"""
    widget = QWidget()
    layout = QVBoxLayout(widget)
    layout.setContentsMargins(0, 0, 0, 0)
    
    # Create active visualizers (only one visible at a time)
    win.waveform_canvas = WaveformLiveCanvas(win, width=8, height=3)
    win.freqdb_canvas = FrequencyDbLiveCanvas(win, width=8, height=3)
    win.fft_bin_canvas = FFTBinBarGraphCanvas(win, width=8, height=3)
    win.waveform_canvas.setVisible(True)  # Start with waveform
    win.freqdb_canvas.setVisible(False)
    win.fft_bin_canvas.setVisible(False)

    layout.addWidget(win.waveform_canvas)
    layout.addWidget(win.freqdb_canvas)
    layout.addWidget(win.fft_bin_canvas)
    
    return widget


def create_position_panel(win) -> QWidget:
    """Alpha/Beta position display"""
    widget = QWidget()
    layout = QVBoxLayout(widget)
    layout.setContentsMargins(0, 0, 0, 0)

    # Position canvas (no rotation - fixed at 0)
    win.position_canvas = PositionCanvas(win, size=2, get_rotation=lambda: 0)
    layout.addWidget(win.position_canvas)

    # Keyboard teaching indicator (dev-only, hidden until activated with Ctrl+Shift+K)
    win._keyboard_teacher_label = QLabel("🎹 OFF")
    win._keyboard_teacher_label.setStyleSheet("color: #666; font-size: 11px;")
    win._keyboard_teacher_label.setVisible(False)
    layout.addWidget(win._keyboard_teacher_label)

    return widget


def create_main_controls_panel(win) -> QWidget:
    """Main stroke controls panel."""
    group = QWidget()
    layout = QHBoxLayout(group)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(10)

    tempo_widget = QWidget()
    tempo_layout = QVBoxLayout(tempo_widget)
    tempo_layout.setContentsMargins(0, 0, 0, 0)
    tempo_layout.setSpacing(4)
    intensity_label = QLabel("Motion Ramp")
    intensity_label.setAlignment(Qt.AlignmentFlag.AlignHCenter)
    intensity_label.setStyleSheet("color: #aaa; margin-top: 8px;")
    tempo_layout.addWidget(intensity_label)
    win.intensity_ramp_spin = SliderWithLabel(
        "Duration (hrs)",
        0.0,
        8.0,
        float(getattr(win.config.stroke, 'intensity_ramp_hours', 0.0) or 0.0),
        2,
        step=0.25,
    )
    win.intensity_ramp_spin.setMinimumWidth(180)
    win.intensity_ramp_spin.setToolTip(
        "Session intensity ramp duration (0 = disabled).\n"
        "Over this many hours, the selected targets ramp\n"
        "from their current values to maximum."
    )
    win.intensity_ramp_spin.valueChanged.connect(
        lambda v: (
            setattr(win.config.stroke, 'intensity_ramp_hours', float(v)),
            win._refresh_motion_ramp_visual_state(),
        )
    )

    win.intensity_ramp_target_combo = QSlider(Qt.Orientation.Horizontal)
    win.intensity_ramp_target_combo.setRange(0, 2)
    win.intensity_ramp_target_combo.setSingleStep(1)
    win.intensity_ramp_target_combo.setPageStep(1)
    win.intensity_ramp_target_combo.setTickInterval(1)
    win.intensity_ramp_target_combo.setTickPosition(QSlider.TickPosition.TicksBelow)
    win.intensity_ramp_target_combo.setMinimumWidth(180)
    current_target = str(getattr(win.config.stroke, 'intensity_ramp_target', 'both') or 'both').strip().lower()
    if current_target not in ('size', 'speed', 'both'):
        current_target = 'both'
    target_to_idx = {'size': 0, 'speed': 1, 'both': 2}
    idx_to_target = {0: 'size', 1: 'speed', 2: 'both'}
    win.intensity_ramp_target_combo.setValue(target_to_idx.get(current_target, 2))
    win.intensity_ramp_target_combo.setToolTip(
        "Choose what the intensity timer affects:\n"
        "Size = orbit & fill pattern expand up to 60 %.\n"
        "Speed = Energy Response ramps from current to max.\n"
        "Both = size + speed simultaneously."
    )
    win.intensity_ramp_target_combo.valueChanged.connect(
        lambda idx: (
            setattr(win.config.stroke, 'intensity_ramp_target', idx_to_target.get(int(idx), 'both')),
            win._refresh_motion_ramp_visual_state(),
        )
    )

    ramp_target_widget = QWidget()
    ramp_target_layout = QVBoxLayout(ramp_target_widget)
    ramp_target_layout.setContentsMargins(0, 0, 0, 0)
    ramp_target_layout.setSpacing(0)
    ramp_target_layout.addWidget(win.intensity_ramp_target_combo)
    ramp_target_labels = QHBoxLayout()
    ramp_target_labels.setContentsMargins(0, 0, 0, 0)
    win.intensity_ramp_target_size_label = QLabel("Size")
    win.intensity_ramp_target_speed_label = QLabel("Speed")
    win.intensity_ramp_target_both_label = QLabel("Both")
    ramp_target_labels.addWidget(win.intensity_ramp_target_size_label, 0, Qt.AlignmentFlag.AlignLeft)
    ramp_target_labels.addWidget(win.intensity_ramp_target_speed_label, 1, Qt.AlignmentFlag.AlignHCenter)
    ramp_target_labels.addWidget(win.intensity_ramp_target_both_label, 0, Qt.AlignmentFlag.AlignRight)
    ramp_target_layout.addLayout(ramp_target_labels)
    win._intensity_ramp_target_labels = {
        'size': win.intensity_ramp_target_size_label,
        'speed': win.intensity_ramp_target_speed_label,
        'both': win.intensity_ramp_target_both_label,
    }

    tempo_layout.addWidget(win.intensity_ramp_spin)
    tempo_layout.addWidget(ramp_target_widget)
    win._refresh_motion_ramp_visual_state()
    tempo_layout.addStretch(1)

    win.fill_gate_scale_spin = SliderWithLabel(
        "Sensitivity",
        1.0,
        100.0,
        win._fill_gate_scale_to_percent(
            float(getattr(win.config.stroke, 'overall_amp_fill_required_scale', 0.5) or 0.5)
        ),
        1,
        step=1.0,
    )
    win.fill_gate_scale_spin.setMinimumWidth(260)
    win.fill_gate_scale_spin.setToolTip(
        "Sensitivity scale (1-100). "
        "Maps to the same internal fill-gate effect range as before."
    )
    win.fill_gate_scale_spin.valueChanged.connect(win._on_fill_gate_scale_change)

    win.pulse_settings_btn = QPushButton("Pulse\nSettings")
    win.pulse_settings_btn.setToolTip("Open Pulse settings popout window")
    win.pulse_settings_btn.clicked.connect(win._on_pulse_settings_popup)
    win.pulse_settings_btn.setFixedSize(76, 76)
    win.pulse_settings_btn.setStyleSheet("text-align: center;")

    win.main_silence_close_slider = SliderWithLabel(
        "Energy Response",
        0.0,
        2.0,
        float(getattr(win.config.stroke, 'energy_response_strength', 1.0)),
        2,
        step=0.01,
    )
    win.main_silence_close_slider.setToolTip(
        "How much extra motion when music is full/energetic.\n"
        "0 = energy has no effect on gates.\n"
        "1 = moderate (default): gates ease ~35% at full energy.\n"
        "2 = strong: gates ease ~70% at full energy."
    )
    win.main_silence_close_slider.setMinimumWidth(260)
    win.main_silence_close_slider.valueChanged.connect(win._on_energy_response_change)
    win._set_energy_response_display(win.main_silence_close_slider.value())

    win._refresh_main_controls_value_label_colors()

    sensitivity_volume_widget = QWidget()
    sensitivity_volume_layout = QVBoxLayout(sensitivity_volume_widget)
    sensitivity_volume_layout.setContentsMargins(0, 0, 0, 0)
    sensitivity_volume_layout.setSpacing(4)
    sensitivity_volume_layout.addWidget(win.fill_gate_scale_spin)
    sensitivity_volume_layout.addWidget(win.main_silence_close_slider)

    for widget in (
        tempo_widget,
        win.pulse_settings_btn,
        sensitivity_volume_widget,
    ):
        widget.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        layout.addWidget(widget, stretch=1)

    win._refresh_motion_ramp_visual_state()
    return group


def create_tcode_freq_tab(win) -> QWidget:
    """Combined Pulse (P0) and Carrier (F0) frequency controls"""
    def _effective_limits(raw_min: float, raw_max: float, default_min: float, default_max: float) -> tuple[float, float]:
        lo = float(raw_min)
        hi = float(raw_max)
        if hi <= lo:
            lo = float(default_min)
            hi = float(default_max)
        return lo, hi

    def _unit_to_tcode(value: float, unit_min: float, unit_max: float) -> int:
        span = max(1e-9, float(unit_max) - float(unit_min))
        norm = (float(value) - float(unit_min)) / span
        return int(max(0, min(9999, round(norm * 9999.0))))

    def _tcode_to_unit(value: int, unit_min: float, unit_max: float) -> float:
        tcode = max(0, min(9999, int(value)))
        return float(unit_min) + (float(tcode) / 9999.0) * (float(unit_max) - float(unit_min))

    def _saved_tcode_units(config_min: int, config_max: int, unit_min: float, unit_max: float) -> tuple[float, float]:
        lo_u = _tcode_to_unit(int(config_min), unit_min, unit_max)
        hi_u = _tcode_to_unit(int(config_max), unit_min, unit_max)
        return min(lo_u, hi_u), max(lo_u, hi_u)

    def _sync_sent_ranges_to_config() -> None:
        p0_out_min_hz, p0_out_max_hz = _effective_limits(win.config.device_limits.p0_freq_min, win.config.device_limits.p0_freq_max, 1.0, 100.0)
        c0_out_min_hz, c0_out_max_hz = _effective_limits(win.config.device_limits.c0_freq_min, win.config.device_limits.c0_freq_max, 500.0, 1500.0)
        p1_out_min, p1_out_max = _effective_limits(win.config.device_limits.p1_cycles_min, win.config.device_limits.p1_cycles_max, 0.0, 20.0)
        p3_out_min, p3_out_max = _effective_limits(win.config.device_limits.p3_cycles_min, win.config.device_limits.p3_cycles_max, 0.0, 20.0)

        p0_sent_min = min(float(win.p0_sent_min_spin.value()), float(win.p0_sent_max_spin.value()))
        p0_sent_max = max(float(win.p0_sent_min_spin.value()), float(win.p0_sent_max_spin.value()))
        win.config.pulse_freq.tcode_min = _unit_to_tcode(p0_sent_min, p0_out_min_hz, p0_out_max_hz)
        win.config.pulse_freq.tcode_max = _unit_to_tcode(p0_sent_max, p0_out_min_hz, p0_out_max_hz)

        f0_sent_min = min(float(win.f0_sent_min_spin.value()), float(win.f0_sent_max_spin.value()))
        f0_sent_max = max(float(win.f0_sent_min_spin.value()), float(win.f0_sent_max_spin.value()))
        win.config.carrier_freq.tcode_min = _unit_to_tcode(f0_sent_min, c0_out_min_hz, c0_out_max_hz)
        win.config.carrier_freq.tcode_max = _unit_to_tcode(f0_sent_max, c0_out_min_hz, c0_out_max_hz)

        p1_sent_min = min(float(win.p1_sent_min_spin.value()), float(win.p1_sent_max_spin.value()))
        p1_sent_max = max(float(win.p1_sent_min_spin.value()), float(win.p1_sent_max_spin.value()))
        win.config.pulse_width.tcode_min = _unit_to_tcode(p1_sent_min, p1_out_min, p1_out_max)
        win.config.pulse_width.tcode_max = _unit_to_tcode(p1_sent_max, p1_out_min, p1_out_max)

        p3_sent_min = min(float(win.p3_sent_min_spin.value()), float(win.p3_sent_max_spin.value()))
        p3_sent_max = max(float(win.p3_sent_min_spin.value()), float(win.p3_sent_max_spin.value()))
        win.config.rise_time.tcode_min = _unit_to_tcode(p3_sent_min, p3_out_min, p3_out_max)
        win.config.rise_time.tcode_max = _unit_to_tcode(p3_sent_max, p3_out_min, p3_out_max)

    class _RangeProxy:
        def __init__(win, low_get, high_get, low_set, high_set, parent_get, blockers):
            win._low_get = low_get
            win._high_get = high_get
            win._low_set = low_set
            win._high_set = high_set
            win._parent_get = parent_get
            win._blockers = list(blockers)

        def low(win):
            return win._low_get()

        def high(win):
            return win._high_get()

        def setLow(win, value):
            win._low_set(value)

        def setHigh(win, value):
            win._high_set(value)

        def parent(win):
            return win._parent_get()

        def blockSignals(win, block: bool):
            for widget in win._blockers:
                if widget is not None:
                    widget.blockSignals(block)

    scroll_area = NoWheelScrollArea()
    scroll_area.setWidgetResizable(True)
    scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
    scroll_area.setStyleSheet(get_thin_scrollbar_style())

    widget = QWidget()
    layout = QVBoxLayout(widget)

    autosave_timer = QTimer(widget)
    autosave_timer.setSingleShot(True)
    autosave_timer.setInterval(500)
    autosave_timer.timeout.connect(lambda: save_config(win.config))

    def _schedule_pulse_spinbox_autosave() -> None:
        autosave_timer.start()

    # ===== PULSE FREQUENCY =====
    pulse_group = CollapsibleGroupBox("Pulse Frequency", collapsed=False)
    pulse_layout = QVBoxLayout(pulse_group)

    dl = win.config.device_limits

    p0_monitor_row = QHBoxLayout()
    p0_monitor_row.addWidget(QLabel("Monitor freq min:"))
    win.p0_monitor_min_spin = QSpinBox()
    win.p0_monitor_min_spin.setRange(20, 500)
    win.p0_monitor_min_spin.setSingleStep(5)
    win.p0_monitor_min_spin.setValue(int(max(20.0, min(500.0, float(win.config.pulse_freq.monitor_freq_min)))))
    win.p0_monitor_min_spin.setSuffix(" Hz")
    p0_monitor_row.addWidget(win.p0_monitor_min_spin)

    p0_monitor_row.addWidget(QLabel("max:"))
    win.p0_monitor_max_spin = QSpinBox()
    win.p0_monitor_max_spin.setRange(20, 500)
    win.p0_monitor_max_spin.setSingleStep(5)
    win.p0_monitor_max_spin.setValue(int(max(20.0, min(500.0, float(win.config.pulse_freq.monitor_freq_max)))))
    win.p0_monitor_max_spin.setSuffix(" Hz")
    p0_monitor_row.addWidget(win.p0_monitor_max_spin)
    p0_monitor_row.addStretch()
    pulse_layout.addLayout(p0_monitor_row)

    p0_out_min_hz, p0_out_max_hz = _effective_limits(dl.p0_freq_min, dl.p0_freq_max, 1.0, 100.0)
    p0_sent_row = QHBoxLayout()
    p0_sent_row.addWidget(QLabel("Sent min:"))
    win.p0_sent_min_spin = QDoubleSpinBox()
    win.p0_sent_min_spin.setRange(float(p0_out_min_hz), float(p0_out_max_hz))
    win.p0_sent_min_spin.setSingleStep(1.0)
    win.p0_sent_min_spin.setDecimals(1)
    p0_saved_min_hz, p0_saved_max_hz = _saved_tcode_units(
        int(getattr(win.config.pulse_freq, 'tcode_min', 2010) or 2010),
        int(getattr(win.config.pulse_freq, 'tcode_max', 7035) or 7035),
        p0_out_min_hz,
        p0_out_max_hz,
    )
    win.p0_sent_min_spin.setValue(float(p0_saved_min_hz))
    win.p0_sent_min_spin.setSuffix(" Hz")
    p0_sent_row.addWidget(win.p0_sent_min_spin)

    p0_sent_row.addWidget(QLabel("max:"))
    win.p0_sent_max_spin = QDoubleSpinBox()
    win.p0_sent_max_spin.setRange(float(p0_out_min_hz), float(p0_out_max_hz))
    win.p0_sent_max_spin.setSingleStep(1.0)
    win.p0_sent_max_spin.setDecimals(1)
    win.p0_sent_max_spin.setValue(float(p0_saved_max_hz))
    win.p0_sent_max_spin.setSuffix(" Hz")
    p0_sent_row.addWidget(win.p0_sent_max_spin)
    p0_sent_row.addStretch()
    pulse_layout.addLayout(p0_sent_row)

    win.freq_weight_slider = SliderWithLabel("Frequency Weight", 0.0, 5.0, 1.0, 2)
    pulse_layout.addWidget(win.freq_weight_slider)

    pulse_mode_layout = QHBoxLayout()
    pulse_mode_layout.addWidget(QLabel("Mode:"))
    win.pulse_mode_combo = QComboBox()
    win.pulse_mode_combo.addItems(["Hz (dominant freq)", "Speed (dot movement)"])
    p0_mode = int(getattr(win.config.pulse_freq, 'mode', 0) or 0)
    win.pulse_mode_combo.setCurrentIndex(max(0, min(1, p0_mode)))
    pulse_mode_layout.addWidget(win.pulse_mode_combo)
    win.pulse_invert_checkbox = QCheckBox("Invert")
    win.pulse_invert_checkbox.setChecked(bool(getattr(win.config.pulse_freq, 'invert', False)))
    pulse_mode_layout.addWidget(win.pulse_invert_checkbox)
    win.pulse_enabled_checkbox = QCheckBox("Enable")
    win.pulse_enabled_checkbox.setChecked(bool(getattr(win.config.pulse_freq, 'enabled', False)))
    pulse_mode_layout.addWidget(win.pulse_enabled_checkbox)
    pulse_mode_layout.addStretch()
    pulse_layout.addLayout(pulse_mode_layout)

    layout.addWidget(pulse_group)

    # ===== CARRIER FREQUENCY =====
    carrier_group = CollapsibleGroupBox("Carrier Frequency", collapsed=False)
    carrier_layout = QVBoxLayout(carrier_group)

    f0_monitor_row = QHBoxLayout()
    f0_monitor_row.addWidget(QLabel("Monitor freq min:"))
    win.f0_monitor_min_spin = QSpinBox()
    win.f0_monitor_min_spin.setRange(20, 500)
    win.f0_monitor_min_spin.setSingleStep(5)
    win.f0_monitor_min_spin.setValue(int(max(20.0, min(500.0, float(win.config.carrier_freq.monitor_freq_min)))))
    win.f0_monitor_min_spin.setSuffix(" Hz")
    f0_monitor_row.addWidget(win.f0_monitor_min_spin)

    f0_monitor_row.addWidget(QLabel("max:"))
    win.f0_monitor_max_spin = QSpinBox()
    win.f0_monitor_max_spin.setRange(20, 500)
    win.f0_monitor_max_spin.setSingleStep(5)
    win.f0_monitor_max_spin.setValue(int(max(20.0, min(500.0, float(win.config.carrier_freq.monitor_freq_max)))))
    win.f0_monitor_max_spin.setSuffix(" Hz")
    f0_monitor_row.addWidget(win.f0_monitor_max_spin)
    f0_monitor_row.addStretch()
    carrier_layout.addLayout(f0_monitor_row)

    c0_out_min_hz, c0_out_max_hz = _effective_limits(dl.c0_freq_min, dl.c0_freq_max, 500.0, 1500.0)
    f0_sent_row = QHBoxLayout()
    f0_sent_row.addWidget(QLabel("Sent min:"))
    win.f0_sent_min_spin = QDoubleSpinBox()
    win.f0_sent_min_spin.setRange(float(c0_out_min_hz), float(c0_out_max_hz))
    win.f0_sent_min_spin.setSingleStep(1.0)
    win.f0_sent_min_spin.setDecimals(1)
    f0_saved_min_hz, f0_saved_max_hz = _saved_tcode_units(
        int(getattr(win.config.carrier_freq, 'tcode_min', 0) or 0),
        int(getattr(win.config.carrier_freq, 'tcode_max', 5000) or 5000),
        c0_out_min_hz,
        c0_out_max_hz,
    )
    win.f0_sent_min_spin.setValue(float(f0_saved_min_hz))
    win.f0_sent_min_spin.setSuffix(" Hz")
    f0_sent_row.addWidget(win.f0_sent_min_spin)

    f0_sent_row.addWidget(QLabel("max:"))
    win.f0_sent_max_spin = QDoubleSpinBox()
    win.f0_sent_max_spin.setRange(float(c0_out_min_hz), float(c0_out_max_hz))
    win.f0_sent_max_spin.setSingleStep(1.0)
    win.f0_sent_max_spin.setDecimals(1)
    win.f0_sent_max_spin.setValue(float(f0_saved_max_hz))
    win.f0_sent_max_spin.setSuffix(" Hz")
    f0_sent_row.addWidget(win.f0_sent_max_spin)
    f0_sent_row.addStretch()
    carrier_layout.addLayout(f0_sent_row)

    win.f0_weight_slider = SliderWithLabel("Frequency Weight", 0.0, 5.0, 1.0, 2)
    carrier_layout.addWidget(win.f0_weight_slider)

    f0_mode_layout = QHBoxLayout()
    f0_mode_layout.addWidget(QLabel("Mode:"))
    win.f0_mode_combo = QComboBox()
    win.f0_mode_combo.addItems(["Hz (dominant freq)", "Speed (dot movement)"])
    f0_mode = int(getattr(win.config.carrier_freq, 'mode', 0) or 0)
    win.f0_mode_combo.setCurrentIndex(max(0, min(1, f0_mode)))
    f0_mode_layout.addWidget(win.f0_mode_combo)
    win.f0_invert_checkbox = QCheckBox("Invert")
    win.f0_invert_checkbox.setChecked(bool(getattr(win.config.carrier_freq, 'invert', False)))
    f0_mode_layout.addWidget(win.f0_invert_checkbox)
    win.f0_enabled_checkbox = QCheckBox("Enable")
    win.f0_enabled_checkbox.setChecked(bool(getattr(win.config.carrier_freq, 'enabled', False)))
    f0_mode_layout.addWidget(win.f0_enabled_checkbox)
    f0_mode_layout.addStretch()
    carrier_layout.addLayout(f0_mode_layout)

    layout.addWidget(carrier_group)

    # ===== PULSE WIDTH =====
    p1_group = CollapsibleGroupBox("Pulse Width — higher = stronger, smoother", collapsed=True)
    p1_layout = QVBoxLayout(p1_group)

    p1_monitor_row = QHBoxLayout()
    p1_monitor_row.addWidget(QLabel("Monitor bass min:"))
    win.p1_monitor_min_spin = QSpinBox()
    win.p1_monitor_min_spin.setRange(20, 500)
    win.p1_monitor_min_spin.setSingleStep(5)
    win.p1_monitor_min_spin.setValue(int(max(20.0, min(500.0, float(win.config.pulse_width.monitor_freq_min)))))
    win.p1_monitor_min_spin.setSuffix(" Hz")
    p1_monitor_row.addWidget(win.p1_monitor_min_spin)

    p1_monitor_row.addWidget(QLabel("max:"))
    win.p1_monitor_max_spin = QSpinBox()
    win.p1_monitor_max_spin.setRange(20, 500)
    win.p1_monitor_max_spin.setSingleStep(5)
    win.p1_monitor_max_spin.setValue(int(max(20.0, min(500.0, float(win.config.pulse_width.monitor_freq_max)))))
    win.p1_monitor_max_spin.setSuffix(" Hz")
    p1_monitor_row.addWidget(win.p1_monitor_max_spin)
    p1_monitor_row.addStretch()
    p1_layout.addLayout(p1_monitor_row)

    p1_out_min, p1_out_max = _effective_limits(dl.p1_cycles_min, dl.p1_cycles_max, 0.0, 20.0)
    p1_sent_row = QHBoxLayout()
    p1_sent_row.addWidget(QLabel("Sent min:"))
    win.p1_sent_min_spin = QDoubleSpinBox()
    win.p1_sent_min_spin.setRange(float(p1_out_min), float(p1_out_max))
    win.p1_sent_min_spin.setSingleStep(0.1)
    win.p1_sent_min_spin.setDecimals(1)
    p1_saved_min, p1_saved_max = _saved_tcode_units(
        int(getattr(win.config.pulse_width, 'tcode_min', 1000) or 1000),
        int(getattr(win.config.pulse_width, 'tcode_max', 8000) or 8000),
        p1_out_min,
        p1_out_max,
    )
    win.p1_sent_min_spin.setValue(float(p1_saved_min))
    win.p1_sent_min_spin.setSuffix(" cyc")
    p1_sent_row.addWidget(win.p1_sent_min_spin)

    p1_sent_row.addWidget(QLabel("max:"))
    win.p1_sent_max_spin = QDoubleSpinBox()
    win.p1_sent_max_spin.setRange(float(p1_out_min), float(p1_out_max))
    win.p1_sent_max_spin.setSingleStep(0.1)
    win.p1_sent_max_spin.setDecimals(1)
    win.p1_sent_max_spin.setValue(float(p1_saved_max))
    win.p1_sent_max_spin.setSuffix(" cyc")
    p1_sent_row.addWidget(win.p1_sent_max_spin)
    p1_sent_row.addStretch()
    p1_layout.addLayout(p1_sent_row)

    win.p1_weight_slider = SliderWithLabel("Weight", 0.0, 5.0, 1.0, 2)
    p1_layout.addWidget(win.p1_weight_slider)

    p1_mode_layout = QHBoxLayout()
    p1_mode_layout.addWidget(QLabel("Mode:"))
    win.p1_mode_combo = QComboBox()
    win.p1_mode_combo.addItems(["Volume (RMS energy)", "Hz (dominant freq)", "Speed (dot movement)"])
    win.p1_mode_combo.setCurrentIndex(0)
    p1_mode_layout.addWidget(win.p1_mode_combo)
    win.p1_invert_checkbox = QCheckBox("Invert")
    win.p1_invert_checkbox.setChecked(False)
    p1_mode_layout.addWidget(win.p1_invert_checkbox)
    win.p1_enabled_checkbox = QCheckBox("Enable")
    win.p1_enabled_checkbox.setChecked(bool(getattr(win, '_cached_p1_enabled', False)))
    p1_mode_layout.addWidget(win.p1_enabled_checkbox)
    p1_mode_layout.addStretch()
    p1_layout.addLayout(p1_mode_layout)

    layout.addWidget(p1_group)

    # ===== RISE TIME =====
    p3_group = CollapsibleGroupBox("Rise Time — higher = smoother, gentler", collapsed=True)
    p3_layout = QVBoxLayout(p3_group)

    p3_monitor_row = QHBoxLayout()
    p3_monitor_row.addWidget(QLabel("Monitor bass min:"))
    win.p3_monitor_min_spin = QSpinBox()
    win.p3_monitor_min_spin.setRange(20, 500)
    win.p3_monitor_min_spin.setSingleStep(5)
    win.p3_monitor_min_spin.setValue(int(max(20.0, min(500.0, float(win.config.rise_time.monitor_freq_min)))))
    win.p3_monitor_min_spin.setSuffix(" Hz")
    p3_monitor_row.addWidget(win.p3_monitor_min_spin)

    p3_monitor_row.addWidget(QLabel("max:"))
    win.p3_monitor_max_spin = QSpinBox()
    win.p3_monitor_max_spin.setRange(20, 500)
    win.p3_monitor_max_spin.setSingleStep(5)
    win.p3_monitor_max_spin.setValue(int(max(20.0, min(500.0, float(win.config.rise_time.monitor_freq_max)))))
    win.p3_monitor_max_spin.setSuffix(" Hz")
    p3_monitor_row.addWidget(win.p3_monitor_max_spin)
    p3_monitor_row.addStretch()
    p3_layout.addLayout(p3_monitor_row)

    p3_out_min, p3_out_max = _effective_limits(dl.p3_cycles_min, dl.p3_cycles_max, 0.0, 20.0)
    p3_sent_row = QHBoxLayout()
    p3_sent_row.addWidget(QLabel("Sent min:"))
    win.p3_sent_min_spin = QDoubleSpinBox()
    win.p3_sent_min_spin.setRange(float(p3_out_min), float(p3_out_max))
    win.p3_sent_min_spin.setSingleStep(0.1)
    win.p3_sent_min_spin.setDecimals(1)
    p3_saved_min, p3_saved_max = _saved_tcode_units(
        int(getattr(win.config.rise_time, 'tcode_min', 1000) or 1000),
        int(getattr(win.config.rise_time, 'tcode_max', 8000) or 8000),
        p3_out_min,
        p3_out_max,
    )
    win.p3_sent_min_spin.setValue(float(p3_saved_min))
    win.p3_sent_min_spin.setSuffix(" cyc")
    p3_sent_row.addWidget(win.p3_sent_min_spin)

    p3_sent_row.addWidget(QLabel("max:"))
    win.p3_sent_max_spin = QDoubleSpinBox()
    win.p3_sent_max_spin.setRange(float(p3_out_min), float(p3_out_max))
    win.p3_sent_max_spin.setSingleStep(0.1)
    win.p3_sent_max_spin.setDecimals(1)
    win.p3_sent_max_spin.setValue(float(p3_saved_max))
    win.p3_sent_max_spin.setSuffix(" cyc")
    p3_sent_row.addWidget(win.p3_sent_max_spin)
    p3_sent_row.addStretch()
    p3_layout.addLayout(p3_sent_row)

    win.p3_weight_slider = SliderWithLabel("Weight", 0.0, 5.0, 1.0, 2)
    p3_layout.addWidget(win.p3_weight_slider)

    p3_mode_layout = QHBoxLayout()
    p3_mode_layout.addWidget(QLabel("Mode:"))
    win.p3_mode_combo = QComboBox()
    win.p3_mode_combo.addItems(["Brightness (spectral centroid)", "Hz (dominant freq)", "Speed (dot movement)"])
    win.p3_mode_combo.setCurrentIndex(0)
    p3_mode_layout.addWidget(win.p3_mode_combo)
    win.p3_invert_checkbox = QCheckBox("Invert")
    win.p3_invert_checkbox.setChecked(False)
    p3_mode_layout.addWidget(win.p3_invert_checkbox)
    win.p3_enabled_checkbox = QCheckBox("Enable")
    win.p3_enabled_checkbox.setChecked(bool(getattr(win, '_cached_p3_enabled', False)))
    p3_mode_layout.addWidget(win.p3_enabled_checkbox)
    p3_mode_layout.addStretch()
    p3_layout.addLayout(p3_mode_layout)

    layout.addWidget(p3_group)

    # Compatibility proxies: preserve existing low()/high()/setLow()/setHigh() call sites.
    win.pulse_freq_range_slider = _RangeProxy(
        low_get=lambda: min(float(win.p0_monitor_min_spin.value()), float(win.p0_monitor_max_spin.value())),
        high_get=lambda: max(float(win.p0_monitor_min_spin.value()), float(win.p0_monitor_max_spin.value())),
        low_set=lambda v: win.p0_monitor_min_spin.setValue(int(v)),
        high_set=lambda v: win.p0_monitor_max_spin.setValue(int(v)),
        parent_get=lambda: win.p0_monitor_min_spin.parent(),
        blockers=(win.p0_monitor_min_spin, win.p0_monitor_max_spin),
    )
    win.f0_freq_range_slider = _RangeProxy(
        low_get=lambda: min(float(win.f0_monitor_min_spin.value()), float(win.f0_monitor_max_spin.value())),
        high_get=lambda: max(float(win.f0_monitor_min_spin.value()), float(win.f0_monitor_max_spin.value())),
        low_set=lambda v: win.f0_monitor_min_spin.setValue(int(v)),
        high_set=lambda v: win.f0_monitor_max_spin.setValue(int(v)),
        parent_get=lambda: win.f0_monitor_min_spin.parent(),
        blockers=(win.f0_monitor_min_spin, win.f0_monitor_max_spin),
    )
    win.p1_monitor_range_slider = _RangeProxy(
        low_get=lambda: min(float(win.p1_monitor_min_spin.value()), float(win.p1_monitor_max_spin.value())),
        high_get=lambda: max(float(win.p1_monitor_min_spin.value()), float(win.p1_monitor_max_spin.value())),
        low_set=lambda v: win.p1_monitor_min_spin.setValue(int(v)),
        high_set=lambda v: win.p1_monitor_max_spin.setValue(int(v)),
        parent_get=lambda: win.p1_monitor_min_spin.parent(),
        blockers=(win.p1_monitor_min_spin, win.p1_monitor_max_spin),
    )
    win.p3_monitor_range_slider = _RangeProxy(
        low_get=lambda: min(float(win.p3_monitor_min_spin.value()), float(win.p3_monitor_max_spin.value())),
        high_get=lambda: max(float(win.p3_monitor_min_spin.value()), float(win.p3_monitor_max_spin.value())),
        low_set=lambda v: win.p3_monitor_min_spin.setValue(int(v)),
        high_set=lambda v: win.p3_monitor_max_spin.setValue(int(v)),
        parent_get=lambda: win.p3_monitor_min_spin.parent(),
        blockers=(win.p3_monitor_min_spin, win.p3_monitor_max_spin),
    )

    win.tcode_freq_range_slider = _RangeProxy(
        low_get=lambda: _unit_to_tcode(
            min(float(win.p0_sent_min_spin.value()), float(win.p0_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.p0_freq_min, win.config.device_limits.p0_freq_max, 1.0, 100.0),
        ),
        high_get=lambda: _unit_to_tcode(
            max(float(win.p0_sent_min_spin.value()), float(win.p0_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.p0_freq_min, win.config.device_limits.p0_freq_max, 1.0, 100.0),
        ),
        low_set=lambda v: win.p0_sent_min_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.p0_freq_min, win.config.device_limits.p0_freq_max, 1.0, 100.0)
        )),
        high_set=lambda v: win.p0_sent_max_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.p0_freq_min, win.config.device_limits.p0_freq_max, 1.0, 100.0)
        )),
        parent_get=lambda: win.p0_sent_min_spin.parent(),
        blockers=(win.p0_sent_min_spin, win.p0_sent_max_spin),
    )
    win.f0_tcode_range_slider = _RangeProxy(
        low_get=lambda: _unit_to_tcode(
            min(float(win.f0_sent_min_spin.value()), float(win.f0_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.c0_freq_min, win.config.device_limits.c0_freq_max, 500.0, 1500.0),
        ),
        high_get=lambda: _unit_to_tcode(
            max(float(win.f0_sent_min_spin.value()), float(win.f0_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.c0_freq_min, win.config.device_limits.c0_freq_max, 500.0, 1500.0),
        ),
        low_set=lambda v: win.f0_sent_min_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.c0_freq_min, win.config.device_limits.c0_freq_max, 500.0, 1500.0)
        )),
        high_set=lambda v: win.f0_sent_max_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.c0_freq_min, win.config.device_limits.c0_freq_max, 500.0, 1500.0)
        )),
        parent_get=lambda: win.f0_sent_min_spin.parent(),
        blockers=(win.f0_sent_min_spin, win.f0_sent_max_spin),
    )
    win.p1_tcode_range_slider = _RangeProxy(
        low_get=lambda: _unit_to_tcode(
            min(float(win.p1_sent_min_spin.value()), float(win.p1_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.p1_cycles_min, win.config.device_limits.p1_cycles_max, 0.0, 20.0),
        ),
        high_get=lambda: _unit_to_tcode(
            max(float(win.p1_sent_min_spin.value()), float(win.p1_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.p1_cycles_min, win.config.device_limits.p1_cycles_max, 0.0, 20.0),
        ),
        low_set=lambda v: win.p1_sent_min_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.p1_cycles_min, win.config.device_limits.p1_cycles_max, 0.0, 20.0)
        )),
        high_set=lambda v: win.p1_sent_max_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.p1_cycles_min, win.config.device_limits.p1_cycles_max, 0.0, 20.0)
        )),
        parent_get=lambda: win.p1_sent_min_spin.parent(),
        blockers=(win.p1_sent_min_spin, win.p1_sent_max_spin),
    )
    win.p3_tcode_range_slider = _RangeProxy(
        low_get=lambda: _unit_to_tcode(
            min(float(win.p3_sent_min_spin.value()), float(win.p3_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.p3_cycles_min, win.config.device_limits.p3_cycles_max, 0.0, 20.0),
        ),
        high_get=lambda: _unit_to_tcode(
            max(float(win.p3_sent_min_spin.value()), float(win.p3_sent_max_spin.value())),
            *_effective_limits(win.config.device_limits.p3_cycles_min, win.config.device_limits.p3_cycles_max, 0.0, 20.0),
        ),
        low_set=lambda v: win.p3_sent_min_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.p3_cycles_min, win.config.device_limits.p3_cycles_max, 0.0, 20.0)
        )),
        high_set=lambda v: win.p3_sent_max_spin.setValue(_tcode_to_unit(
            int(v), *_effective_limits(win.config.device_limits.p3_cycles_min, win.config.device_limits.p3_cycles_max, 0.0, 20.0)
        )),
        parent_get=lambda: win.p3_sent_min_spin.parent(),
        blockers=(win.p3_sent_min_spin, win.p3_sent_max_spin),
    )

    # Keep callbacks/overlays in sync when spinboxes change.
    win.p0_monitor_min_spin.valueChanged.connect(lambda *_: win._on_p0_band_change())
    win.p0_monitor_max_spin.valueChanged.connect(lambda *_: win._on_p0_band_change())
    win.f0_monitor_min_spin.valueChanged.connect(lambda *_: win._on_f0_band_change())
    win.f0_monitor_max_spin.valueChanged.connect(lambda *_: win._on_f0_band_change())
    win.p1_monitor_min_spin.valueChanged.connect(lambda *_: win._on_p1_band_change())
    win.p1_monitor_max_spin.valueChanged.connect(lambda *_: win._on_p1_band_change())
    win.p3_monitor_min_spin.valueChanged.connect(lambda *_: win._on_p3_band_change())
    win.p3_monitor_max_spin.valueChanged.connect(lambda *_: win._on_p3_band_change())

    win.p0_monitor_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p0_monitor_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.f0_monitor_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.f0_monitor_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p1_monitor_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p1_monitor_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p3_monitor_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p3_monitor_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())

    win.p0_sent_min_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.p0_sent_max_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.f0_sent_min_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.f0_sent_max_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.p1_sent_min_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.p1_sent_max_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.p3_sent_min_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())
    win.p3_sent_max_spin.valueChanged.connect(lambda *_: _sync_sent_ranges_to_config())

    win.p0_sent_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p0_sent_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.f0_sent_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.f0_sent_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p1_sent_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p1_sent_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p3_sent_min_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    win.p3_sent_max_spin.valueChanged.connect(lambda *_: _schedule_pulse_spinbox_autosave())
    _sync_sent_ranges_to_config()

    layout.addStretch()
    scroll_area.setWidget(widget)
    return scroll_area


def create_beat_detection_tab(win) -> QWidget:
    """Beat detection settings with vertical scroll"""
    # Outer scroll area (no wheel to prevent interference with parameter sliders)
    scroll_area = NoWheelScrollArea()
    scroll_area.setWidgetResizable(True)
    scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
    scroll_area.setStyleSheet(get_thin_scrollbar_style())
    
    # Content widget inside scroll area
    widget = QWidget()
    layout = QVBoxLayout(widget)
    
    # Detection type
    type_layout = QHBoxLayout()
    type_layout.addWidget(QLabel("Detection Type:"))
    win.detection_type_combo = QComboBox()
    win.detection_type_combo.addItems(["Peak Energy", "Spectral Flux", "Combined"])
    win.detection_type_combo.setCurrentIndex(2)  # Combined
    win.detection_type_combo.currentIndexChanged.connect(win._on_detection_type_change)
    type_layout.addWidget(win.detection_type_combo)
    type_layout.addStretch()
    # Wrap detection type in a groupbox
    detect_group = QGroupBox("Detection")
    detect_layout = QVBoxLayout(detect_group)
    detect_layout.addLayout(type_layout)

    # Global auto-adjust toggle moved to top Detection group
    win.metrics_global_cb = QCheckBox("Enable Auto-Adjust")
    win.metrics_global_cb.setChecked(win.config.auto_adjust.metrics_global_enabled)
    win.metrics_global_cb.setToolTip("Master toggle for all auto-adjust controls")
    win.metrics_global_cb.setStyleSheet("font-weight: bold; font-size: 10px;")
    win.metrics_global_cb.stateChanged.connect(win._on_metrics_global_toggle)
    detect_layout.addWidget(win.metrics_global_cb)

    layout.addWidget(detect_group)

    # Everything below detection type lives inside one windowshade section
    auto_levels_group = CollapsibleGroupBox("Auto-Levels", collapsed=True)
    auto_levels_layout = QVBoxLayout(auto_levels_group)

    # ===== AUTO-ADJUST (METRIC-BASED AUTO-RANGING) =====
    metric_layout = auto_levels_layout
    
    # Butterworth filter (mandatory for metrics)
    win.butterworth_checkbox = QCheckBox("Butterworth bandpass filter")
    win.butterworth_checkbox.setChecked(getattr(win.config.audio, 'use_butterworth', True))
    win.butterworth_checkbox.stateChanged.connect(win._on_butterworth_toggle)
    metric_layout.addWidget(win.butterworth_checkbox)
    
    # Metric controls row
    metric_ctrl_layout = QHBoxLayout()
    
    win.metric_audio_amp_cb = QCheckBox("Audio Amp (Beat)")
    win.metric_audio_amp_cb.setToolTip("No beats → raise audio_amp 2%/1.1s | Excess beats → lower audio_amp")
    win.metric_audio_amp_cb.stateChanged.connect(lambda state: win._on_metric_toggle('audio_amp', state == 2))
    metric_ctrl_layout.addWidget(win.metric_audio_amp_cb)
    
    metric_ctrl_layout.addStretch()
    metric_layout.addLayout(metric_ctrl_layout)

    win.metric_speed_slider = SliderWithLabel(
        "Auto-Adjust Speed",
        0.5,
        3.0,
        getattr(win.config.auto_adjust, 'metric_response_speed', 1.0),
        2
    )
    win.metric_speed_slider.valueChanged.connect(win._on_metric_response_speed_change)
    metric_layout.addWidget(win.metric_speed_slider)
    
    # Metric status label only (traffic light moved to control panel)
    status_row = QHBoxLayout()
    win.metric_status_label = QLabel("Metrics: [idle]")
    win.metric_status_label.setStyleSheet("color: #AAA; font-size: 9px;")
    status_row.addWidget(win.metric_status_label)
    status_row.addStretch()
    metric_layout.addLayout(status_row)
    
    # Enable metrics based on config (first load = True, then saved)
    global_on = win.config.auto_adjust.metrics_global_enabled
    win.metric_audio_amp_cb.setChecked(global_on)
    if global_on:
        print("[Config] Auto-enabled Audio Amp metric from config")

    # ===== LEVELS: Audio Amplification, Sensitivity, Flux Multiplier =====
    levels_layout = auto_levels_layout
    
    # Frequency band selection with visibility toggle (red beat detection band)
    beat_slider_row = QHBoxLayout()
    win.freq_range_slider = RangeSliderWithLabel("Freq Range (Hz)", 30, 22050, 100, 8000, 0, log_scale=True)
    win.freq_range_slider.rangeChanged.connect(win._on_freq_band_change)
    beat_slider_row.addWidget(win.freq_range_slider)
    levels_layout.addLayout(beat_slider_row)
    
    # Audio amplification/gain: boost weak signals (0.15=quiet, 5.0=loud)
    aa_min, aa_max = BEAT_RANGE_LIMITS['audio_amp']
    win.audio_gain_slider = SliderWithLabel("Audio Amplification", aa_min, aa_max, win.config.audio.gain, 2)
    win.audio_gain_slider.valueChanged.connect(lambda v: setattr(win.config.audio, 'gain', v))
    levels_layout.addWidget(win.audio_gain_slider)
    
    # Sensitivity: higher = more beats detected (0.0=strict, 1.0=very sensitive)
    sens_min, sens_max = BEAT_RANGE_LIMITS['sensitivity']
    win.sensitivity_slider = SliderWithLabel("Sensitivity", sens_min, sens_max, win.config.beat.sensitivity)
    win.sensitivity_slider.valueChanged.connect(lambda v: setattr(win.config.beat, 'sensitivity', v))
    levels_layout.addWidget(win.sensitivity_slider)
    
    # Z-Score Threshold: lower = more z-score beats, higher = fewer (1.0-5.0)
    win.zscore_threshold_slider = SliderWithLabel("Z-Score Sens", 1.0, 5.0, 4.0)
    win.zscore_threshold_slider.valueChanged.connect(win._on_zscore_threshold_change)
    levels_layout.addWidget(win.zscore_threshold_slider)
    
    # Flux Multiplier
    fm_min, fm_max = BEAT_RANGE_LIMITS['flux_mult']
    win.flux_mult_slider = SliderWithLabel("Flux Multiplier", fm_min, fm_max, win.config.beat.flux_multiplier, 2)
    win.flux_mult_slider.valueChanged.connect(lambda v: setattr(win.config.beat, 'flux_multiplier', v))
    levels_layout.addWidget(win.flux_mult_slider)
    

    # ===== DEPTH/PEAKS: Depth, Peak Decay, Rise Sensitivity =====
    peaks_layout = auto_levels_layout
    
    # Peak floor: minimum energy to consider (0 = disabled)
    # Range 0.01-0.15: typical band_energy is 0.08-0.15 with default gain
    pf_min, pf_max = BEAT_RANGE_LIMITS['peak_floor']
    win.peak_floor_slider = SliderWithLabel("Depth", pf_min, pf_max, win.config.beat.peak_floor, 3)
    win.peak_floor_slider.valueChanged.connect(lambda v: setattr(win.config.beat, 'peak_floor', v))
    peaks_layout.addWidget(win.peak_floor_slider)
    
    # Peak decay
    pd_min, pd_max = BEAT_RANGE_LIMITS['peak_decay']
    win.peak_decay_slider = SliderWithLabel("Peak Decay", pd_min, pd_max, win.config.beat.peak_decay, 3)
    win.peak_decay_slider.valueChanged.connect(lambda v: setattr(win.config.beat, 'peak_decay', v))
    peaks_layout.addWidget(win.peak_decay_slider)
    
    # Rise sensitivity: 0 = disabled, higher = require more rise
    rs_min, rs_max = BEAT_RANGE_LIMITS['rise_sens']
    win.rise_sens_slider = SliderWithLabel("Rise Sensitivity", rs_min, rs_max, win.config.beat.rise_sensitivity)
    win.rise_sens_slider.valueChanged.connect(lambda v: setattr(win.config.beat, 'rise_sensitivity', v))
    peaks_layout.addWidget(win.rise_sens_slider)
    
    layout.addWidget(auto_levels_group)
    
    layout.addStretch()
    scroll_area.setWidget(widget)
    return scroll_area


def create_tempo_response_group(win, lock_default: bool = True) -> QGroupBox:
    """Advanced tempo-response controls group used in Tempo Tracking popout."""
    tempo_resp_group = QGroupBox("Advanced Tempo Controls")
    tempo_resp_layout = QVBoxLayout(tempo_resp_group)

    lock_cb = QCheckBox("Lock advanced tempo controls")
    lock_cb.setChecked(bool(lock_default))
    lock_cb.setToolTip("Lock/unlock advanced tempo tracking tuning controls in this group")
    tempo_resp_layout.addWidget(lock_cb)

    tempo_resp_info = QLabel("Tune lock/relock speed and phase correction behavior.\nLower smoothing = faster response, higher can be steadier.")
    tempo_resp_info.setStyleSheet("color: #aaa; font-size: 11px;")
    tempo_resp_layout.addWidget(tempo_resp_info)

    def _set_slider_row_tooltip(widget: SliderWithLabel, text: str):
        widget.setToolTip(text)
        widget.label.setToolTip(text)
        widget.slider.setToolTip(text)
        widget.value_label.setToolTip(text)

    acf_row = QHBoxLayout()
    acf_label = QLabel("ACF interval (ms):")
    acf_label.setStyleSheet("color: #ccc;")
    acf_row.addWidget(acf_label)
    acf_spin = QSpinBox()
    acf_spin.setMinimum(150)
    acf_spin.setMaximum(800)
    acf_spin.setSingleStep(10)
    acf_spin.setValue(int(getattr(win.config.beat, 'acf_interval_ms', 250)))
    acf_spin.setToolTip("How often to run ACF tempo estimation")
    acf_label.setToolTip("How often to run ACF tempo estimation. Lower = faster tempo updates, higher = steadier updates.")
    acf_spin.valueChanged.connect(partial(win._on_tempo_param_change, 'acf_interval_ms', '_acf_interval_ms', transform=float))
    acf_row.addWidget(acf_spin)
    tempo_resp_layout.addLayout(acf_row)

    alpha_slow_slider = SliderWithLabel("BPM Adaptation (Uncertain)", 0.01, 0.20, getattr(win.config.beat, 'metronome_bpm_alpha_slow', 0.03), 3)
    alpha_slow_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'metronome_bpm_alpha_slow', '_metronome_bpm_alpha_slow'))
    _set_slider_row_tooltip(alpha_slow_slider, "How fast BPM locks when beat signal is unclear. Lower = safer, slower lock; Higher = aggressive adaptation")
    tempo_resp_layout.addWidget(alpha_slow_slider)

    alpha_fast_slider = SliderWithLabel("BPM Adaptation (Confident)", 0.05, 0.40, getattr(win.config.beat, 'metronome_bpm_alpha_fast', 0.22), 3)
    alpha_fast_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'metronome_bpm_alpha_fast', '_metronome_bpm_alpha_fast'))
    _set_slider_row_tooltip(alpha_fast_slider, "How fast BPM locks when beat is strong and clear. Lower = stable, conservative; Higher = snappy response")
    tempo_resp_layout.addWidget(alpha_fast_slider)

    pll_window_slider = SliderWithLabel("Timing Flex Window", 0.10, 0.50, getattr(win.config.beat, 'metronome_pll_window', 0.35), 2)
    pll_window_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'metronome_pll_window', '_metronome_pll_window'))
    _set_slider_row_tooltip(pll_window_slider, "How much timing drift (as beat fraction) allowed before auto-correction kicks in. Higher = more tolerant; Lower = stricter")
    tempo_resp_layout.addWidget(pll_window_slider)

    pll_base_slider = SliderWithLabel("Timing Correction Strength", 0.01, 0.20, getattr(win.config.beat, 'metronome_pll_base_gain', 0.09), 3)
    pll_base_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'metronome_pll_base_gain', '_metronome_pll_base_gain'))
    _set_slider_row_tooltip(pll_base_slider, "How aggressively to adjust timing when out of sync. Lower = laid-back/behind-the-beat feel; Higher = tight/ahead tracking")
    tempo_resp_layout.addWidget(pll_base_slider)

    pll_conf_slider = SliderWithLabel("Confidence Boost", 0.00, 0.20, getattr(win.config.beat, 'metronome_pll_conf_gain', 0.08), 3)
    pll_conf_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'metronome_pll_conf_gain', '_metronome_pll_conf_gain'))
    _set_slider_row_tooltip(pll_conf_slider, "Extra timing correction when beat lock is solid. Amplifies the correction intensity. Lower = stable when locked; Higher = responsive")
    tempo_resp_layout.addWidget(pll_conf_slider)

    fusion_min_slider = SliderWithLabel("Fusion min ACF wt", 0.00, 0.80, getattr(win.config.beat, 'tempo_fusion_min_acf_weight', 0.20), 2)
    fusion_min_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'tempo_fusion_min_acf_weight', '_tempo_fusion_min_acf_weight'))
    _set_slider_row_tooltip(fusion_min_slider, "Minimum ACF contribution when blending ACF BPM with onset BPM.")
    tempo_resp_layout.addWidget(fusion_min_slider)

    fusion_max_slider = SliderWithLabel("Fusion max ACF wt", 0.20, 1.00, getattr(win.config.beat, 'tempo_fusion_max_acf_weight', 0.95), 2)
    fusion_max_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'tempo_fusion_max_acf_weight', '_tempo_fusion_max_acf_weight'))
    _set_slider_row_tooltip(fusion_max_slider, "Maximum ACF contribution when confidence is high.")
    tempo_resp_layout.addWidget(fusion_max_slider)

    dedup_slider = SliderWithLabel("Beat de-dup frac", 0.10, 0.35, getattr(win.config.beat, 'beat_dedup_fraction', 0.22), 2)
    dedup_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'beat_dedup_fraction', '_beat_dedup_fraction'))
    _set_slider_row_tooltip(dedup_slider, "Reject a second raw onset if it arrives within this fraction of the current beat period. Reduces double-beat chatter.")
    tempo_resp_layout.addWidget(dedup_slider)

    phase_accept_slider = SliderWithLabel("Phase accept win ms", 20.0, 220.0, getattr(win.config.beat, 'phase_accept_window_ms', 85.0), 0)
    phase_accept_slider.valueChanged.connect(
        lambda v: partial(win._on_tempo_param_change, 'phase_accept_window_ms', '_phase_accept_window_ms', transform=float)(v)
    )
    _set_slider_row_tooltip(phase_accept_slider, "Accept raw onsets only when they are this close (ms) to expected beat phase.")
    tempo_resp_layout.addWidget(phase_accept_slider)

    low_conf_mult_slider = SliderWithLabel("Low-conf win x", 1.00, 3.50, getattr(win.config.beat, 'phase_accept_low_conf_mult', 2.0), 2)
    low_conf_mult_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'phase_accept_low_conf_mult', '_phase_accept_low_conf_mult'))
    _set_slider_row_tooltip(low_conf_mult_slider, "Multiplies phase-accept window when confidence is low, so relock stays flexible.")
    tempo_resp_layout.addWidget(low_conf_mult_slider)

    octave_target_bias_slider = SliderWithLabel(
        "Target-hint max conf",
        0.05,
        0.80,
        getattr(win.config.beat, 'octave_target_bias_confidence_max', 0.35),
        2,
    )
    octave_target_bias_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'octave_target_bias_confidence_max', '_octave_target_bias_confidence_max'))
    _set_slider_row_tooltip(
        octave_target_bias_slider,
        "Only use target BPM to guide octave disambiguation below this ACF confidence."
    )
    tempo_resp_layout.addWidget(octave_target_bias_slider)

    aggressive_snap_cb = QCheckBox("Aggressive tempo snap when lock is confident")
    aggressive_snap_cb.setChecked(getattr(win.config.beat, 'aggressive_tempo_snap_enabled', False))
    aggressive_snap_cb.setToolTip("When enabled, metronome BPM can hard-snap to target under strict confidence/phase safeguards.")
    aggressive_snap_cb.stateChanged.connect(lambda state: win._on_aggressive_tempo_snap_toggle(state == 2))
    tempo_resp_layout.addWidget(aggressive_snap_cb)

    snap_conf_slider = SliderWithLabel("Snap min confidence", 0.20, 0.90, getattr(win.config.beat, 'aggressive_snap_confidence', 0.55), 2)
    snap_conf_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'aggressive_snap_confidence', '_aggressive_snap_confidence'))
    _set_slider_row_tooltip(snap_conf_slider, "Minimum ACF confidence required before aggressive snap is allowed.")
    tempo_resp_layout.addWidget(snap_conf_slider)

    snap_phase_slider = SliderWithLabel("Snap max phase err ms", 10.0, 120.0, getattr(win.config.beat, 'aggressive_snap_phase_error_ms', 35.0), 0)
    snap_phase_slider.valueChanged.connect(
        lambda v: partial(win._on_tempo_param_change, 'aggressive_snap_phase_error_ms', '_aggressive_snap_phase_error_ms', transform=float)(v)
    )
    _set_slider_row_tooltip(snap_phase_slider, "Only snap if beat phase error is below this many milliseconds.")
    tempo_resp_layout.addWidget(snap_phase_slider)

    snap_jump_slider = SliderWithLabel("Snap max BPM jump", 0.03, 0.30, getattr(win.config.beat, 'aggressive_snap_max_bpm_jump_ratio', 0.12), 2)
    snap_jump_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'aggressive_snap_max_bpm_jump_ratio', '_aggressive_snap_max_bpm_jump_ratio'))
    _set_slider_row_tooltip(snap_jump_slider, "Maximum one-step relative BPM change allowed during aggressive snap.")
    tempo_resp_layout.addWidget(snap_jump_slider)

    snap_match_row = QHBoxLayout()
    snap_match_label = QLabel("Snap min downbeat matches:")
    snap_match_label.setStyleSheet("color: #ccc;")
    snap_match_row.addWidget(snap_match_label)
    snap_match_spin = QSpinBox()
    snap_match_spin.setMinimum(0)
    snap_match_spin.setMaximum(4)
    snap_match_spin.setValue(int(getattr(win.config.beat, 'aggressive_snap_min_matches', 1)))
    snap_match_label.setToolTip("Require this many matching downbeats before aggressive tempo snap can trigger.")
    snap_match_spin.setToolTip("Require this many matching downbeats before aggressive tempo snap can trigger.")
    snap_match_spin.valueChanged.connect(partial(win._on_tempo_param_change, 'aggressive_snap_min_matches', '_aggressive_snap_min_matches', transform=int))
    snap_match_row.addWidget(snap_match_spin)
    tempo_resp_layout.addLayout(snap_match_row)

    reset_tempo_btn = QPushButton("Reset Tempo Response Defaults")
    reset_tempo_btn.setToolTip("Restore default values for all tempo-response tuning controls")

    def _reset_tempo_response_defaults():
        acf_spin.setValue(250)
        alpha_slow_slider.setValue(0.03)
        alpha_fast_slider.setValue(0.22)
        pll_window_slider.setValue(0.35)
        pll_base_slider.setValue(0.09)
        pll_conf_slider.setValue(0.08)
        fusion_min_slider.setValue(0.20)
        fusion_max_slider.setValue(0.95)
        dedup_slider.setValue(0.22)
        phase_accept_slider.setValue(85.0)
        low_conf_mult_slider.setValue(2.0)
        octave_target_bias_slider.setValue(0.35)
        aggressive_snap_cb.setChecked(False)
        snap_conf_slider.setValue(0.55)
        snap_phase_slider.setValue(35.0)
        snap_jump_slider.setValue(0.12)
        snap_match_spin.setValue(1)

    reset_tempo_btn.clicked.connect(_reset_tempo_response_defaults)
    tempo_resp_layout.addWidget(reset_tempo_btn)

    advanced_targets = [
        acf_label,
        acf_spin,
        alpha_slow_slider,
        alpha_fast_slider,
        pll_window_slider,
        pll_base_slider,
        pll_conf_slider,
        fusion_min_slider,
        fusion_max_slider,
        dedup_slider,
        phase_accept_slider,
        low_conf_mult_slider,
        octave_target_bias_slider,
        aggressive_snap_cb,
        snap_conf_slider,
        snap_phase_slider,
        snap_jump_slider,
        snap_match_label,
        snap_match_spin,
        reset_tempo_btn,
    ]

    def _apply_advanced_lock_state() -> None:
        locked = bool(lock_cb.isChecked())
        for widget in advanced_targets:
            widget.setEnabled(not locked)

    lock_cb.stateChanged.connect(lambda _: _apply_advanced_lock_state())
    _apply_advanced_lock_state()
    return tempo_resp_group


def create_tempo_tracking_tab(win, include_advanced_controls: bool = False, advanced_locked: bool = True) -> QWidget:
    """Tempo tracking and rhythm settings"""
    scroll_area = NoWheelScrollArea()
    scroll_area.setWidgetResizable(True)
    scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)

    widget = QWidget()
    layout = QVBoxLayout(widget)

    # ===== TEMPO SETTINGS =====
    tempo_group = CollapsibleGroupBox("Tempo Settings", collapsed=False)
    tempo_layout = QVBoxLayout(tempo_group)
    
    # Enable/disable checkbox
    win.tempo_tracking_checkbox = QCheckBox("Enable Tempo Tracking")
    win.tempo_tracking_checkbox.setChecked(True)
    win.tempo_tracking_checkbox.stateChanged.connect(win._on_tempo_tracking_toggle)
    tempo_layout.addWidget(win.tempo_tracking_checkbox)

    win.tempo_settings_lock_cb = QCheckBox("Lock tempo settings")
    win.tempo_settings_lock_cb.setChecked(False)
    win.tempo_settings_lock_cb.setToolTip("Lock/unlock tempo tuning controls in this group")
    win.tempo_settings_lock_cb.stateChanged.connect(win._on_tempo_settings_lock_toggle)
    tempo_layout.addWidget(win.tempo_settings_lock_cb)
    
    # Time signature dropdown
    sig_layout = QHBoxLayout()
    sig_layout.addWidget(QLabel("Time Signature:"))
    win.time_sig_combo = QComboBox()
    win.time_sig_combo.addItems(["4/4 (4 beats)", "3/4 (3 beats)", "6/8 (6 beats)"])
    win.time_sig_combo.currentIndexChanged.connect(win._on_time_sig_change)
    sig_layout.addWidget(win.time_sig_combo)
    sig_layout.addStretch()
    tempo_layout.addLayout(sig_layout)
    
    # Stability threshold: lower = stricter (requires more consistent intervals before locking BPM)
    win.stability_threshold_slider = SliderWithLabel("Stability Threshold", 0.05, 0.4, 0.15, 2)
    win.stability_threshold_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'stability_threshold', 'stability_threshold'))
    tempo_layout.addWidget(win.stability_threshold_slider)
    
    # Tempo timeout: how long no beats before resetting tempo tracking
    win.tempo_timeout_slider = SliderWithLabel("Tempo Timeout (ms)", 500, 5000, 2000, 0)
    win.tempo_timeout_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'tempo_timeout_ms', 'tempo_timeout_ms', transform=int))
    tempo_layout.addWidget(win.tempo_timeout_slider)
    
    # Phase snap: how much to nudge detected beats toward predicted time
    win.phase_snap_slider = SliderWithLabel("Phase Snap", 0.0, 0.8, 0.3, 2)
    win.phase_snap_slider.valueChanged.connect(partial(win._on_tempo_param_change, 'phase_snap_weight', 'phase_snap_weight'))
    tempo_layout.addWidget(win.phase_snap_slider)
    
    # Silence reset threshold (moved from Beat Detection)
    win.silence_reset_slider = SliderWithLabel("Silence Reset (ms)", 100, 3000, 180, 0)
    win.silence_reset_slider.valueChanged.connect(lambda v: setattr(win.config.beat, 'silence_reset_ms', int(v)))
    tempo_layout.addWidget(win.silence_reset_slider)

    win._tempo_settings_lock_targets = [
        win.time_sig_combo,
        win.stability_threshold_slider,
        win.tempo_timeout_slider,
        win.phase_snap_slider,
        win.silence_reset_slider,
    ]

    win._apply_tempo_settings_enabled_state(win.tempo_tracking_checkbox.isChecked())
    
    layout.addWidget(tempo_group)

    if include_advanced_controls:
        layout.addWidget(win._create_tempo_response_group(lock_default=advanced_locked))
    
    layout.addStretch()
    scroll_area.setWidget(widget)
    return scroll_area

# Event handlers

